#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3308/eco_stack?characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create

spring:
  data:
    mongodb:
      uri : mongodb://localhost:27017/eco_stack
 #     uri: mongodb://133.186.216.34:27017/eco_stack

server:
  port: 8080